### ISSUE TITLE
Reduce size STL for Realsense camera

### ISSUE THREAD

**Issue by deebuls** [b-it-bots/technical_drawings#3]
The STL seems to be 20 MB in size.

Can you reduces the size @hkhbrus ? 
Maybe reduce teh number of triangles or meshes.

**Comment by deebuls** [comment]
@hkhbrus please look into this

**Comment by deebuls** [comment]
Also please mention the size of the model ? and what units is used .

**Comment by HAndradi** [comment]
I have reduced the file sizes to 5.8 & 7.8 MB. I can reduce the file sizes further if required. The length and width of both the models are 60 and 36 mm respectively. The height of Mount 1 is 54.2 mm and the height of Mount 2 is 16.7 mm. I can also make detailed drawings of the parts if required. 

Two M3 x 5mm screws are required to attach the camera to the mount. If the length of the screws available are slightly longer or shorter, I can change the 3D models accordingly.

**Comment by deebuls** [comment]
@hkhbrus  Thanks for the update.

Yes please reduce it.
Can it be less than  1 MB ?

**Comment by HAndradi** [comment]
Yes, I reduced both files to less than 1 MB each.

**Comment by deebuls** [comment]
@hkhbrus  I got 1 of it 3D printed. You can have a look in the C025 lab.

**Comment by deebuls** [comment]
@hkhbrus  Good work !! The camera fits properly. 

Its really appreciated how fast and accurate you can design the models as per requirements.

Closing this issue now. Thanks again.
